name: reciclaanda2
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_swiper: ^1.1.6
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_staggered_grid_view: ^0.3.0
  cloud_firestore: ^0.12.9
  carousel_pro: ^1.0.0
  transparent_image: ^1.0.0
  scoped_model: ^1.0.1
  firebase_auth: ^0.11.1+12
  url_launcher: ^5.1.1
  introduction_screen: ^1.0.7
  dots_indicator : ^ 1.2.0
  webview_flutter: ^1.0.7
  flutter_launcher_icons: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  # assets:
  assets:
    - assets/images/intoscreen_1.png
    - assets/images/intoscreen_2.png
    - assets/images/intoscreen_3.png
    - assets/images/intoscreen_4.png
    - assets/images/intoscreen_5.png
    - assets/images/curved.jpg
    - assets/images/logo_descarte.png
    - assets/images/linha_azul.jpg
    - assets/images/card_home.png
    - assets/images/lixeiras-coleta-seletiva.jpg
    - assets/images/engenheiros.jpg
    - assets/images/eletroportateis.jpg
    - assets/images/o_que_e_lixo_eletronico.jpg
    - assets/images/lixo_eletronico.jpg
    - assets/images/linha_verde.jpg
    - assets/images/linha_verde.png
    - assets/images/linha_marrom.jpg
    - assets/images/linha_branca.png
    - assets/images/linha_azuls.jpg
    - assets/images/linha_azul_screen.jpg
    - assets/images/linha_verde_screen.jpg
    - assets/images/linha_branca_screen.jpg
    - assets/images/linha_marrom_screen.jpg
    - assets/images/linha_especial_screen.jpg
    - assets/images/linha_spacial.jpg
    - assets/images/7_engineers.jpg
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/reciclaanda.png"